theme: "just-the-docs" 

baseurl: /Connected-Interaction-Kit/test

title: Connected Interaction Kit
color_scheme: connected-interaction-kit

plugins:
  - jekyll-redirect-from

callouts_level: quiet
callouts:
  highlight:
    color: red
  highlight-yellow:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: red
  note-purple:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


# External navigation links
nav_external_links:
  - title: Digital Interfaces
    url: https://id-studiolab.github.io/Digital-Interfaces/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: CircuitPython Docs
    url: https://docs.circuitpython.org/en/latest/README.html
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
